CREATE DATABASE IF NOT EXISTS usuario_paises CHARACTER SET utf8 COLLATE  utf8_general_ci;

INSERT INTO `pais` (`id`, `nombre`, `capital`) VALUES
(1, 'España', 'Madrid'),
(2, 'Francia', 'París'),
(3, 'Alemania', 'Berlín'),
(4, 'Reino Unido', 'Londres'),
(5, 'Portugal', 'Lisboa'),
(6, 'Italia', 'Roma'),
(7, 'Austria', 'Viena'),
(8, 'Suiza', 'Berna'),
(9, 'Chequia', 'Praga'),
(10, 'Bulgaria', 'Sofía'),
(11, 'Polonia', 'Varsovia'),
(12, 'Serbia', 'Belgrado'),
(13, 'Bosnia', 'Sarajevo'),
(14, 'Croacia', 'Zagreb'),
(15, 'Macedonia', 'Skopje'),
(16, 'Noruega', 'Oslo'),
(17, 'Suecia', 'Estocolmo'),
(18, 'Grecia', 'Atenas'),
(19, 'Dinamarca', 'Copenhaghue'),
(20, 'Finlandia', 'Helsinki'),
(21, 'Albania', 'Tirana'),
(22, 'Belgica', 'Bruselas'),
(23, 'Chipre', 'Nicosia'),
(24, 'Eslovaquia', 'Bratislava'),
(25, 'Eslovenia', 'Luibliana'),
(26, 'Estonia', 'Tallin'),
(27, 'Hungria', 'Budapest'),
(28, 'Irlanda', 'Dublín'),
(29, 'Islandia', 'Reikiavik'),
(30, 'Kosovo', 'Pristina'),
(31, 'Letonia', 'Riga'),
(32, 'Rumanía', 'Bucarest'),
(33, 'Lituania', 'Vilna'),
(34, 'Luxemburgo', 'Luxemburgo'),
(35, 'Malta', 'La Valeta'),
(36, 'Moldavia', 'Chisnáu'),
(37, 'Montenegro', 'Podgorica'),
(38, 'Ucrania', 'Kiev'),
(39, 'Andorra', 'Andorra la Vella'),
(40, 'Mónaco', 'Mónaco'),
(41, 'Países Bajos', 'Amsterdam'),
(42, 'Rusia', 'Moscú'),
(43, 'Bielorrusia', 'Minsk'),
(44, 'Vaticano', 'Vaticano'),
(45, 'San Marino', 'San Marino'),
(46, 'Liechtenstein', 'Vaduz');
